language: node_js
node_js:
  - "6.10.3"
env:
  global:
    - AWS_REGION=fake
    - AWS_SECRET_ACCESS_KEY=fake
    - AWS_ACCESS_KEY_ID=fake
before_script:
  - echo "Setting up DynamoDB"
  - wget http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest.tar.gz -O /tmp/dynamodb_local_latest.tar.gz
  - tar -xzf /tmp/dynamodb_local_latest.tar.gz -C /tmp
  - java -Djava.library.path=/tmp/DynamoDBLocal_lib -jar /tmp/DynamoDBLocal.jar -sharedDb &
  - sleep 5
